// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using todoAPI.Models;

namespace todoapi.Migrations
{
    [DbContext(typeof(todoAPIContext))]
    [Migration("20220823194941_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("todoAPI.Models.ToDo", b =>
                {
                    b.Property<int>("ToDoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Image")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("PP")
                        .HasColumnType("int");

                    b.HasKey("ToDoId");

                    b.ToTable("ToDos");

                    b.HasData(
                        new
                        {
                            ToDoId = 1,
                            Category = "Personal",
                            Description = "Walks your dog",
                            Image = "https://cdn.discordapp.com/attachments/1011292802468032512/1011680146673123339/wakawaka.png",
                            Name = "Waka-Waka",
                            PP = 68
                        },
                        new
                        {
                            ToDoId = 2,
                            Category = "Home",
                            Description = "Does your laundry",
                            Image = "https://cdn.discordapp.com/attachments/1011292802468032512/1011687033116299284/waashmo.png",
                            Name = "Waashmo",
                            PP = 2
                        },
                        new
                        {
                            ToDoId = 3,
                            Category = "Personal",
                            Description = "Does your taxes",
                            Image = "https://cdn.discordapp.com/attachments/1011292802468032512/1011386221441847326/irirs.png",
                            Name = "Irirs",
                            PP = 67
                        },
                        new
                        {
                            ToDoId = 4,
                            Category = "Food",
                            Description = "Buys you groceries",
                            Image = "https://cdn.discordapp.com/attachments/1011292802468032512/1011342412297281606/munchakoopa.png",
                            Name = "Munchakoopa",
                            PP = 7
                        },
                        new
                        {
                            ToDoId = 5,
                            Category = "School",
                            Description = "Does your Epicodus homework",
                            Image = "https://cdn.discordapp.com/attachments/1011292802468032512/1011344877369425930/monyay.png",
                            Name = "Monyay",
                            PP = 70
                        },
                        new
                        {
                            ToDoId = 6,
                            Category = "Personal",
                            Description = "Your own personal trainer",
                            Image = "https://cdn.discordapp.com/attachments/1011292802468032512/1011682719232704632/swolium.png",
                            Name = "Swolium",
                            PP = 89
                        },
                        new
                        {
                            ToDoId = 7,
                            Category = "Home",
                            Description = "Waters your indoor plants",
                            Image = "https://cdn.discordapp.com/attachments/1011292802468032512/1011688286126870598/cannowat.png",
                            Name = "Cannowat",
                            PP = 15
                        },
                        new
                        {
                            ToDoId = 8,
                            Category = "Personal",
                            Description = "Cuts your hair",
                            Image = "https://cdn.discordapp.com/attachments/1011292802468032512/1011347425161654292/snips.png",
                            Name = "Snips",
                            PP = 80
                        },
                        new
                        {
                            ToDoId = 9,
                            Category = "Car",
                            Description = "Changes your oil",
                            Image = "https://cdn.discordapp.com/attachments/1011292802468032512/1011368404504031342/jiffyum.png",
                            Name = "Jiffyum",
                            PP = 93
                        },
                        new
                        {
                            ToDoId = 10,
                            Category = "Home",
                            Description = "Pays your rent",
                            Image = "https://cdn.discordapp.com/attachments/1011292802468032512/1011387943673397318/arm_and_leg.png",
                            Name = "Arm and Leg",
                            PP = 27
                        },
                        new
                        {
                            ToDoId = 11,
                            Category = "Home",
                            Description = "Vacuums your house",
                            Image = "https://cdn.discordapp.com/attachments/1011292802468032512/1011348731750252655/Suckuebus.png",
                            Name = "Suckuebus",
                            PP = 53
                        },
                        new
                        {
                            ToDoId = 12,
                            Category = "Car",
                            Description = "Goes to the DMV",
                            Image = "https://cdn.discordapp.com/attachments/1011292802468032512/1011689057723613305/waiterus.png",
                            Name = "Waiterus",
                            PP = 42
                        },
                        new
                        {
                            ToDoId = 13,
                            Category = "Personal",
                            Description = "Plans the wedding",
                            Image = "https://cdn.discordapp.com/attachments/1011292802468032512/1011722626709860442/wedder.png",
                            Name = "Wedder",
                            PP = 33
                        },
                        new
                        {
                            ToDoId = 14,
                            Category = "Food",
                            Description = "Preps all your meals",
                            Image = "https://cdn.discordapp.com/attachments/1011292802468032512/1011670067211153439/DinDin.png",
                            Name = "DinDin",
                            PP = 48
                        },
                        new
                        {
                            ToDoId = 15,
                            Category = "Personal",
                            Description = "Goes to the library",
                            Image = "https://cdn.discordapp.com/attachments/1011292802468032512/1011686587882549341/Booksi.png",
                            Name = "Booksi",
                            PP = 61
                        },
                        new
                        {
                            ToDoId = 16,
                            Category = "Car",
                            Description = "Fills your tank a little",
                            Image = "https://cdn.discordapp.com/attachments/1011292802468032512/1011340622675845281/50_bucks.png",
                            Name = "50 Bucks",
                            PP = 57
                        },
                        new
                        {
                            ToDoId = 17,
                            Category = "Personal",
                            Description = "Forces you to watch Hotrod",
                            Image = "https://cdn.discordapp.com/attachments/1011292802468032512/1011359277492998294/rodded.png",
                            Name = "Rodded",
                            PP = 88
                        },
                        new
                        {
                            ToDoId = 18,
                            Category = "Health",
                            Description = "Extracts and donates your blood",
                            Image = "https://cdn.discordapp.com/attachments/1011292802468032512/1011357411883364512/vamps.png",
                            Name = "Vamp",
                            PP = 65
                        },
                        new
                        {
                            ToDoId = 19,
                            Category = "Home",
                            Description = "Mows your lawn",
                            Image = "https://cdn.discordapp.com/attachments/1011292802468032512/1011686667708551189/Momo.png",
                            Name = "Momo",
                            PP = 34
                        },
                        new
                        {
                            ToDoId = 20,
                            Category = "Home",
                            Description = "Fixes your sink",
                            Image = "https://cdn.discordapp.com/attachments/1011292802468032512/1011687294954110986/PlumpPlumber.png",
                            Name = "Plump Plumber",
                            PP = 11
                        },
                        new
                        {
                            ToDoId = 21,
                            Category = "Health",
                            Description = "Meditates ... or just sleeps",
                            Image = "https://cdn.discordapp.com/attachments/1011292802468032512/1011420092384428133/medichu.png",
                            Name = "Medichu",
                            PP = 100
                        },
                        new
                        {
                            ToDoId = 22,
                            Category = "Health",
                            Description = "Manditory colonoscopy: you must make a copy of your colons",
                            Image = "https://cdn.discordapp.com/attachments/1011292802468032512/1011362297127649351/CloseCall.png",
                            Name = "Close Call",
                            PP = 34
                        },
                        new
                        {
                            ToDoId = 23,
                            Category = "School",
                            Description = "Makes you do a technical interview",
                            Image = "https://cdn.discordapp.com/attachments/1011292802468032512/1011686543003504750/WhiteBoardPuff.png",
                            Name = "Whiteboardpuff",
                            PP = 15
                        },
                        new
                        {
                            ToDoId = 24,
                            Category = "Personal",
                            Description = "Checks your credit score - damages your credit",
                            Image = "https://cdn.discordapp.com/attachments/1011292802468032512/1011686725837406280/Loanio.png",
                            Name = "Loanio",
                            PP = 67
                        },
                        new
                        {
                            ToDoId = 25,
                            Category = "Home",
                            Description = "Replaces batteries in smoke detectors",
                            Image = "https://cdn.discordapp.com/attachments/1011292802468032512/1011393369731248220/smokey.png",
                            Name = "Smokey",
                            PP = 90
                        },
                        new
                        {
                            ToDoId = 26,
                            Category = "Car",
                            Description = "Washes your car with a dirty rag",
                            Image = "https://cdn.discordapp.com/attachments/1011292802468032512/1011349207539515453/Carwash.png",
                            Name = "WashyCar",
                            PP = 76
                        },
                        new
                        {
                            ToDoId = 27,
                            Category = "Personal",
                            Description = "Gives you one free massage",
                            Image = "https://cdn.discordapp.com/attachments/1011292802468032512/1011716974822305842/hamassage.png",
                            Name = "Hamassage",
                            PP = 51
                        },
                        new
                        {
                            ToDoId = 28,
                            Category = "Food",
                            Description = "Makes you eat a ghost pepper",
                            Image = "https://cdn.discordapp.com/attachments/1011292802468032512/1011390601897455686/ghostgarper.png",
                            Name = "Ghostgarper",
                            PP = 0
                        },
                        new
                        {
                            ToDoId = 29,
                            Category = "Home",
                            Description = "Flips your mattress for no reason",
                            Image = "https://cdn.discordapp.com/attachments/1011292802468032512/1011686784633143346/FlipMonChan.png",
                            Name = "Flipmonchan",
                            PP = 0
                        },
                        new
                        {
                            ToDoId = 30,
                            Category = "Home",
                            Description = "Takes out your trash",
                            Image = "https://cdn.discordapp.com/attachments/1011292802468032512/1011684166254993498/trashpinch.png",
                            Name = "Trashpinch",
                            PP = 0
                        },
                        new
                        {
                            ToDoId = 31,
                            Category = "Home",
                            Description = "Gets your mail - shreds it",
                            Image = "https://cdn.discordapp.com/attachments/1011292802468032512/1011682850715750460/mailapod.png",
                            Name = "Mailapod",
                            PP = 0
                        },
                        new
                        {
                            ToDoId = 32,
                            Category = "Home",
                            Description = "Cleans your dishes without soap",
                            Image = "https://cdn.discordapp.com/attachments/1011292802468032512/1011395918093893722/MR_Dirty.png",
                            Name = "Mr. Dirty",
                            PP = 0
                        },
                        new
                        {
                            ToDoId = 33,
                            Category = "Food",
                            Description = "Bakes cookies - burns them",
                            Image = "https://cdn.discordapp.com/attachments/1011292802468032512/1011687059389427732/CookieTron.png",
                            Name = "Cookietron",
                            PP = 0
                        },
                        new
                        {
                            ToDoId = 34,
                            Category = "Personal",
                            Description = "Plans Carl's funeral",
                            Image = "https://cdn.discordapp.com/attachments/1011292802468032512/1011687190692106360/CarlsDad.png",
                            Name = "Carl's Dad",
                            PP = 3
                        },
                        new
                        {
                            ToDoId = 35,
                            Category = "School",
                            Description = "Makes your README file - never credits you",
                            Image = "https://cdn.discordapp.com/attachments/1011292802468032512/1011718304840294481/SeekZaTenShun.png",
                            Name = "Seekzatenshun",
                            PP = 0
                        },
                        new
                        {
                            ToDoId = 36,
                            Category = "School",
                            Description = "Updates your resume with their name and contact info",
                            Image = "https://cdn.discordapp.com/attachments/1011292802468032512/1011720274082791494/resumoocher.png",
                            Name = "Jobbofind",
                            PP = 0
                        },
                        new
                        {
                            ToDoId = 37,
                            Category = "Home",
                            Description = "Mops your floor with too much soap",
                            Image = "https://cdn.discordapp.com/attachments/1011292802468032512/1011686475169026048/Moprog.png",
                            Name = "Moprog",
                            PP = 0
                        },
                        new
                        {
                            ToDoId = 38,
                            Category = "Personal",
                            Description = "You must speed run Darksouls",
                            Image = "https://cdn.discordapp.com/attachments/1011292802468032512/1011415353122889879/you_died.png",
                            Name = "You Died",
                            PP = 0
                        },
                        new
                        {
                            ToDoId = 39,
                            Category = "Personal",
                            Description = "Takes a bath - you no longer have a bath",
                            Image = "https://cdn.discordapp.com/attachments/1011292802468032512/1011417800079847494/scrubadubdub.png",
                            Name = "Scrubadubdub",
                            PP = 0
                        },
                        new
                        {
                            ToDoId = 40,
                            Category = "Health",
                            Description = "Time to get your flu shot",
                            Image = "https://cdn.discordapp.com/attachments/1011292802468032512/1011686915407360000/JustALittlePrick.png",
                            Name = "Justa 'Lil Prick",
                            PP = 0
                        },
                        new
                        {
                            ToDoId = 41,
                            Category = "Work",
                            Description = "Rings whenever you forget a semicolon",
                            Image = "https://cdn.discordapp.com/attachments/1011292802468032512/1011686999729639585/Remiu.png",
                            Name = "Remiu",
                            PP = 0
                        },
                        new
                        {
                            ToDoId = 42,
                            Category = "Food",
                            Description = "Cleans out your fridge entirely",
                            Image = "https://cdn.discordapp.com/attachments/1011292802468032512/1011687090943168552/Clefridgy.png",
                            Name = "Clefridgy",
                            PP = 0
                        },
                        new
                        {
                            ToDoId = 43,
                            Category = "Personal",
                            Description = "Teaches you how to dance",
                            Image = "https://cdn.discordapp.com/attachments/1011292802468032512/1011417750452830228/unknown.png",
                            Name = "ChaCha-mon",
                            PP = 0
                        },
                        new
                        {
                            ToDoId = 44,
                            Category = "Personal",
                            Description = "Invests in bitcoin and in your future",
                            Image = "https://cdn.discordapp.com/attachments/1011292802468032512/1011401474997223455/unknown.png",
                            Name = "MoneyBanks",
                            PP = 0
                        },
                        new
                        {
                            ToDoId = 45,
                            Category = "Food",
                            Description = "Eats your whole roll of Cookiedough as fast as he can",
                            Image = "https://cdn.discordapp.com/attachments/1011292802468032512/1011686842841698314/SantasHelper.png",
                            Name = "Santa's Helper",
                            PP = 0
                        },
                        new
                        {
                            ToDoId = 46,
                            Category = "Food",
                            Description = "Solves world hunger; doesn't tell you how",
                            Image = "https://cdn.discordapp.com/attachments/1011292802468032512/1011419920761892904/unknown.png",
                            Name = "Grincheon",
                            PP = 0
                        },
                        new
                        {
                            ToDoId = 47,
                            Category = "Work",
                            Description = "Simply walks into Mordor",
                            Image = "https://cdn.discordapp.com/attachments/1011292802468032512/1011685949102628905/wondusnot.png",
                            Name = "Wondusnot",
                            PP = 0
                        },
                        new
                        {
                            ToDoId = 48,
                            Category = "Personal",
                            Description = "Finds Nemo - doesn't tell you where",
                            Image = "https://cdn.discordapp.com/attachments/1011292802468032512/1011361910991630467/Find_nemo.png",
                            Name = "Marlout",
                            PP = 0
                        },
                        new
                        {
                            ToDoId = 49,
                            Category = "Health",
                            Description = "Kills Sarah Connor - legally",
                            Image = "https://cdn.discordapp.com/attachments/1011292802468032512/1011680839869927575/unknown.png",
                            Name = "B-back 7000",
                            PP = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
